### ISSUE TITLE
ModuleNotFoundError: No module named 'dash_pdf._imports_'

### ISSUE THREAD

**Issue by yoshisatose** [ploomber/dash-pdf#1]
Thank you for your efforts. This will be very helpful for me.
Because I could not find this package as a library in Pypi, I first cloned the git repo and install as follows:

git clone https://github.com/ploomber/dash-pdf.git
cd dash-pdf/
python setup.py install

It seems that the installation was successful. However, when I tried to import dash_pdf, I got an error:

> import dash_pdf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jupyter/dash-pdf/dash_pdf/__init__.py", line 10, in <module>
    from ._imports_ import *
ModuleNotFoundError: No module named 'dash_pdf._imports_'

How can I solve this issue?

**Comment by edublancas** [comment]
@yoshisatose I uploaded this to PyPI, let me know if it works!

```
pip install dash-pdf
```

**Comment by edublancas** [comment]
closing due to inactivity, feel free to open if you have more issues

**Comment by yoshisatose** [comment]
Thank you. It worked.
